apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint
spec:
  limits:
  - default: 
    defaultRequest: 
      cpu: 100m
    max: 
      cpu: 500m
    min:
      cpu: 100m

    type: Container
    