kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: {{ include "helm-chart.appName" . }}-ns
  name: deny-traffic-from-other-namespaces
spec:
  podSelector:
    matchLabels:
  ingress:
  - from:
    - podSelector: {}