# BACKEND

apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-chart.appName" . }}-service
spec:
  selector:
    app: {{ include "helm-chart.appName" . }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

  type: ClusterIP

---

# DATABASE

apiVersion: v1
kind: Service
metadata:
  labels:
    app: dynamodb
  name: {{ include "helm-chart.appName" . }}-dynamodb-service
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: dynamodb
  
  type: ClusterIP
    
