apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "helm-chart.appName" . }}-pvc
spec:
  storageClassName: cloud-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
      
---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cloud-ssd
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer